"""Curated reference-range table for the demo markers.

THIS IS THE ONLY SOURCE OF REFERENCE RANGES. They are hand-curated and must never
be generated by the model. Values are conservative, adult general-reference bands
for a prototype demo — not clinical advice and not personalized.

For each marker:
  * ``low`` / ``high``  -> the in-range interval bounds.
  * ``amber_margin``    -> width of the caution band just *inside* the concerning
                           boundary. A value inside the range but within this margin
                           of the concerning bound is amber (approaching out-of-range).

Which boundary is "concerning" is driven by the marker's ``direction_of_concern``
(see ``markers_catalog``): "up" -> the high bound, "down" -> the low bound,
"both" -> either bound.
"""

from __future__ import annotations

from pydantic import BaseModel


class ReferenceRange(BaseModel):
    marker_id: str
    low: float
    high: float
    amber_margin: float


REFERENCE_RANGES: dict[str, ReferenceRange] = {
    "glucose_fasting": ReferenceRange(marker_id="glucose_fasting", low=70, high=99, amber_margin=8),
    "hba1c": ReferenceRange(marker_id="hba1c", low=4.0, high=5.6, amber_margin=0.3),
    "chol_total": ReferenceRange(marker_id="chol_total", low=0, high=199, amber_margin=20),
    "ldl": ReferenceRange(marker_id="ldl", low=0, high=99, amber_margin=15),
    "hdl": ReferenceRange(marker_id="hdl", low=40, high=100, amber_margin=5),
    "triglycerides": ReferenceRange(marker_id="triglycerides", low=0, high=149, amber_margin=20),
    "creatinine": ReferenceRange(marker_id="creatinine", low=0.7, high=1.3, amber_margin=0.1),
    "alt": ReferenceRange(marker_id="alt", low=7, high=56, amber_margin=6),
    "tsh": ReferenceRange(marker_id="tsh", low=0.4, high=4.0, amber_margin=0.4),
    "vitamin_d": ReferenceRange(marker_id="vitamin_d", low=30, high=100, amber_margin=5),
    "hemoglobin": ReferenceRange(marker_id="hemoglobin", low=13.5, high=17.5, amber_margin=0.5),
}


def get_range(marker_id: str) -> ReferenceRange:
    """Return the curated reference range for ``marker_id`` or raise KeyError."""
    return REFERENCE_RANGES[marker_id]
